# Generated by Django 3.0.2 on 2020-01-05 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200104_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(editable=False)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField()),
                ('commented_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='web.Post')),
            ],
        ),
    ]
